version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"
            - "disableStutteringCheck"

formatters:
  enable:
    - gofmt
    - goimports
